### ISSUE TITLE
喻波说的没错，建议提高英语背单词的打卡率

### ISSUE THREAD

**Issue by xueyu888** [OOCC/PlanGIt#2]
@OOCC/ooc 我发现90%确实太简单了，为了迎接新年的到来，我建议把打卡率要求提高到**95%以上**，各位觉得如何？投票决定（回复数字123）：

1.  同意
2.  不同意，维持现状
3.  不同意，更高要求或者更低要求，请备注

**Comment by xueyu888** [comment]
1

**Comment by luoyefeisong** [comment]
与 @Ananaxs 达成一致，打卡率要达到100%，未达到者踢出小组。特殊原因忘打卡可利用时光机来补

**Comment by xueyu888** [comment]
与 @Ananaxs 达成一致，打卡率要达到100%，未达到者踢出小组。特殊原因忘打卡可利用时光机来补
